schen237Project4: src1.o src2.o src3.o
	gcc -o schen237Project4 src1.o src2.o src3.o

src1.o: src1.c header.h
	gcc -c src1.c

src2.o: src2.c header.h
	gcc -c src2.c

src3.o: src3.c header.h
	gcc -c src3.c

clean:
	rm src1.o src2.o src3.o schen237Project4


